sudo: false
language: java
jdk:
  - oraclejdk7
addons:
  apt:
    packages:
      - rpm
before_deploy:
  - mvn jdeb:jdeb && export RELEASE_DEB_FILE=$(ls target/*.deb)
  - mvn rpm:rpm && export RELEASE_RPM_FILE=$(find target/ -name '*.rpm' | tail -1)
  - rm -f target/original-*.jar
  - export RELEASE_PKG_FILE=$(ls target/*.jar)
  - echo "Deploying release to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: WjBIPIkPOfg4GNywJTY1E8+CZtBxSi77FkprGpMQuc87vCUrPJXd+U8WyK9k/EuIrJ/ZhsmzkYwWl16cSwi/35oQSkj8GJM3AyBXzauX6FqM3nWK91hPwkxnIflAInQkg2C6z64bYiyiEWq7ZhVAqbg7yIquVyqO5MMpvBHwAA1DEELXgq1AqJyRxe31itoSOKCjxO2DIPjk61LEPmU/zNBRoF1zQ9BZ/stmi5fm71XBtXrSRzXqqb+0UTY17HTDxfwk7SeP2EvFmKtk7oB6LrD6/XURMM6wKcIt74ND59+5G0lEpTrSmPmMhfcgAH9Rc/RdXacJI7xj+z1FoXyt8aGPBOFKF2ZrGFy9bJPwoJKHFnY0riTFtFzOaMKAuwk1cpqsX9fnKwNBrCXJqMYOtrEAqCqt2yzUCfs4fyMY3Gb3QuxCB9AF3+ahqWSAKKDId92Xbpx4GYlqkGu6KUMQBQbpA2I5texG4kirk4NZ7AY31pM3GXB+XRlR5fvh28CmYAu3oeZII90tEs6FvHGsxwyd+WGOJziG3YrPZ4ChBKP5ARvjtHBvJIxDdL0Cd2DTKbYeblcUFKhfUmwDoqy49h8I+VbtU2ZhIJm6M/7/MXMCLSeLQNsTTKwB0SQMvM6VjW0ezL3XyiIgEoZxakeZ/uMzXA1VtigpDVqpP9XLVqg=
  file:
    - "${RELEASE_PKG_FILE}"
    - "${RELEASE_DEB_FILE}"
    - "${RELEASE_RPM_FILE}"
  skip_cleanup: true
  on:
    tags: true
    jdk: oraclejdk7
